server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 25MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

